language: python
python:
  - "3.6"
sudo: required
services:
  - docker
script:
  - python3 generate.py
  - python3 build.py
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
after_success:
  - bash ./notify.sh