language: python
python:
  - "3.6"
sudo: required
services:
  - docker
script:
  - python3 generate.py
  - python3 build.py
  - docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_USERNAME"
after_success:
  - bash ./notify.sh