language: python
python:
  - "3.6"
sudo: required
services:
  - docker
script:
  - python3 generate.py
after_success:
  - curl -X POST -H 'Content-type: application/json' --data '{"text":"Blender Docker images deployed to Docker Hub :party:", "icon_emoji": ":blender-3d:"}' ${WEBHOOK_URL}